import React, { useState } from 'react';
import { Pressable, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { AppScreen } from '../components/POSUI';
import { usePOS } from '../hooks/usePOS';
import { TaxDefinition } from '../models/pos';
import { useAppTheme } from '../theme';
export function TaxesScreen() {
 const { state,hasPermission,upsertTaxDefinition,deleteTaxDefinition,lastCatalogSyncAt,catalogSyncError,syncCatalog }=usePOS();
 const theme=useAppTheme(); const editable=hasPermission('manage_catalog');
 const [editing,setEditing]=useState<TaxDefinition|null>(null);const [name,setName]=useState('');const [rate,setRate]=useState('');
 const [enabled,setEnabled]=useState(true);const [isDefault,setDefault]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [confirm,setConfirm]=useState<string|null>(null);
 function reset(){setEditing(null);setName('');setRate('');setEnabled(true);setDefault(false);}
 async function save(){if(busy)return;const value=Number(rate);if(!name.trim()||!rate.trim()||!Number.isFinite(value)||value<0||value>100){setError('Enter a name and a rate from 0% to 100%.');return;}
  setBusy(true);setError(null);try{await upsertTaxDefinition({id:editing?.id??'new-tax',name:name.trim(),rate:value,enabled,isDefault,updatedAt:editing?.updatedAt});reset();}catch(cause){setError(cause instanceof Error?cause.message:'Unable to save tax.');}finally{setBusy(false);}}
 async function archive(id:string){if(confirm!==id){setConfirm(id);return;}setBusy(true);try{await deleteTaxDefinition(id);setConfirm(null);reset();}catch(cause){setError(cause instanceof Error?cause.message:'Unable to archive tax.');}finally{setBusy(false);}}
 const card={backgroundColor:theme.colors.surface,borderColor:theme.colors.border};
 return <AppScreen title="Taxes" subtitle="Shared with your dashboard and connected registers.">
  <View style={[styles.card,card]}><Text style={[styles.heading,{color:theme.colors.text}]}>{state.settings.business.pricesIncludeTax?'Business prices include tax':'Business prices exclude tax'}</Text><Text style={{color:theme.colors.textMuted}}>Default taxes apply to unassigned taxable items. Exempt items stay tax free.</Text><Text style={{color:theme.colors.textMuted}}>{lastCatalogSyncAt?`Last sync ${new Date(lastCatalogSyncAt).toLocaleTimeString()}`:'Waiting for first sync'}</Text><Pressable accessibilityRole="button" style={styles.action} onPress={()=>syncCatalog().catch(cause=>setError(cause.message))}><Text style={{color:theme.colors.accent}}>Refresh settings</Text></Pressable></View>
  {(error||catalogSyncError)&&<Text accessibilityRole="alert" style={{color:theme.colors.danger}}>{error||catalogSyncError}</Text>}
  {!state.settings.business.taxDefinitions.length&&<Text style={{color:theme.colors.textMuted}}>No tax rates configured. {editable?'Create the rates your business uses below.':'Ask a manager to configure your taxes.'}</Text>}
  {state.settings.business.taxDefinitions.filter(tax=>!tax.archived).map(tax=><View key={tax.id} style={[styles.card,card]}><Text style={[styles.heading,{color:theme.colors.text}]}>{tax.name} · {tax.rate}%</Text><Text style={{color:theme.colors.textMuted}}>{tax.enabled?'Enabled':'Disabled'}{tax.isDefault?' · Business default':''} · {state.products.filter(p=>p.taxIds?.includes(tax.id)).length} assigned items</Text>{editable&&<View style={styles.actions}><Pressable style={styles.action} disabled={busy} accessibilityRole="button" onPress={()=>{setEditing(tax);setName(tax.name);setRate(String(tax.rate));setEnabled(tax.enabled);setDefault(tax.isDefault===true);}}><Text style={{color:theme.colors.accent}}>Edit</Text></Pressable><Pressable style={styles.action} disabled={busy} accessibilityRole="button" onPress={()=>archive(tax.id)}><Text style={{color:theme.colors.danger}}>{confirm===tax.id?'Confirm archive':'Archive'}</Text></Pressable></View>}</View>)}
  {editable&&<View style={[styles.card,card]}><Text style={[styles.heading,{color:theme.colors.text}]}>{editing?'Edit tax':'Create tax'}</Text><TextInput accessibilityLabel="Tax name" placeholder="Tax name" placeholderTextColor={theme.colors.textMuted} value={name} onChangeText={setName} style={[styles.input,{color:theme.colors.text,borderColor:theme.colors.border}]}/><TextInput accessibilityLabel="Tax percentage" placeholder="Rate (%)" placeholderTextColor={theme.colors.textMuted} keyboardType="decimal-pad" value={rate} onChangeText={setRate} style={[styles.input,{color:theme.colors.text,borderColor:theme.colors.border}]}/><View style={styles.toggle}><Text style={{color:theme.colors.text}}>Enabled</Text><Switch accessibilityLabel="Tax enabled" value={enabled} onValueChange={setEnabled}/></View><View style={styles.toggle}><Text style={{color:theme.colors.text}}>Business default</Text><Switch accessibilityLabel="Business default tax" value={isDefault} onValueChange={setDefault}/></View><View style={styles.actions}><Pressable disabled={busy} style={[styles.button,{backgroundColor:theme.colors.accent}]} accessibilityRole="button" onPress={()=>save()}><Text style={{color:theme.colors.accentText}}>{busy?'Saving…':'Save tax'}</Text></Pressable>{editing&&<Pressable style={styles.action} onPress={reset}><Text style={{color:theme.colors.text}}>Cancel</Text></Pressable>}</View></View>}
 </AppScreen>;
}
const styles=StyleSheet.create({card:{padding:20,borderWidth:1,borderRadius:12,gap:12},heading:{fontSize:18,fontWeight:'600'},input:{minHeight:48,fontSize:16,borderWidth:1,borderRadius:8,paddingHorizontal:12},toggle:{minHeight:48,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},actions:{flexDirection:'row',gap:12,flexWrap:'wrap'},action:{minHeight:48,minWidth:64,justifyContent:'center',paddingHorizontal:8},button:{minHeight:48,paddingHorizontal:20,borderRadius:8,justifyContent:'center'}});
