import { Transaction,TransactionItem } from '../../models/pos';
import { apiClient } from './ApiClient';
type Order = {id:string;local_order_id:string;reference_code:string;status:string;currency:string;created_at:string;subtotal_in_cents:number;discount_in_cents:number;tax_in_cents:number;total_in_cents:number;refunded_in_cents:number;receipt_snapshot?:Transaction['receipt'];payment?:{provider:string;payment_method:string}};
function mapOrder(order:Order):Transaction{return {id:order.local_order_id,referenceCode:order.reference_code,createdAt:order.created_at,subtotal:order.subtotal_in_cents-order.discount_in_cents,tax:order.tax_in_cents,total:order.total_in_cents,currency:order.currency==='usd'?'USD':'CAD',status:order.status==='refunded'?'refunded':order.status==='partially_refunded'?'partially_refunded':order.status==='paid'?'approved':'pending',paymentMethod:order.payment?.provider==='cash'?'cash':'card_reader',paymentProvider:order.payment?.provider==='cash'?'cash':'stripe_terminal',serverSyncStatus:'synced',serverOrderId:order.id,refundedAmount:order.refunded_in_cents,receipt:order.receipt_snapshot,items:[]};}
export async function fetchOrders(cursor?:string){const result=await apiClient.get<{data:{orders:Order[];nextCursor:string|null}}>(`/api/orders?limit=50${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`);return {transactions:result.data.orders.map(mapOrder),nextCursor:result.data.nextCursor};}
export async function fetchOrderDetail(id:string):Promise<Transaction>{
 const result=await apiClient.get<{data:{order:Order;items:Array<Record<string,unknown>>;payments:Array<Record<string,unknown>>;staff?:{id:string;name:string};customer?:Transaction['customer'];refunds?:Array<Record<string,unknown>>}}>(`/api/orders/${id}`);
 const detail=result.data;const payment=detail.payments[0];
 const items=detail.items.map(item=>({id:String(item.id),productId:typeof item.product_id==='string'?item.product_id:undefined,name:String(item.product_name),quantity:Number(item.quantity),unitPriceInCents:Number(item.unit_price_in_cents),discountInCents:Number(item.discount_in_cents),taxInCents:Number(item.tax_in_cents),totalInCents:Number(item.total_in_cents),type:item.product_id?'product':'custom',taxable:Number(item.tax_in_cents)>0,metadata:item.metadata, taxLines:(item.metadata as {taxLines?:TransactionItem['taxLines']})?.taxLines} as TransactionItem));
 const taxMap=new Map<string,NonNullable<Transaction['taxLines']>[number]>();for(const item of items)for(const tax of item.taxLines??[]){const previous=taxMap.get(tax.taxId);taxMap.set(tax.taxId,{...tax,amount:(previous?.amount??0)+tax.amount});}
 return {...mapOrder(detail.order),items,taxLines:[...taxMap.values()],staff:detail.staff,customer:detail.customer??undefined,paymentMethod:payment?.provider==='cash'?'cash':'card_reader',paymentProvider:payment?.provider==='cash'?'cash':'stripe_terminal',processorReference:typeof payment?.provider_payment_id==='string'?payment.provider_payment_id:undefined,cashDetails:payment?.provider==='cash'?{receivedInCents:Number(payment.cash_received_in_cents),changeGivenInCents:Number(payment.change_given_in_cents)}:undefined};
}
